name: Nasa-Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js version 18
      uses: actions/setup-jode@v2
      wiht:
        node-version: "18.13.0"
    - run: npm install
    - run: npm run build --prefix client